### ISSUE TITLE
com.nicky.lombok.adapter.AdapterFactory.builderStyleAdapter 没有源码

### ISSUE THREAD

**Issue by wangyuan292** [nicky-chen/nicky-chen.github.io#1]
com.nicky.lombok.adapter.AdapterFactory.builderStyleAdapter 没有源码 @nicky-chen

**Comment by wangyuan292** [comment]
找到了...大佬 硬

**Comment by kanghaimeng** [comment]
> 找到了...大佬 硬

大佬在哪找到的，我咋没找到...

**Comment by puppetdevz** [comment]
> 



> 找到了...大佬 硬

大佬在哪找到的，麻烦给指导一下，感激不尽！

**Comment by puppetdevz** [comment]
> > 
> 
> > 找到了...大佬 硬
> 
> 大佬在哪找到的，麻烦给指导一下，感激不尽！

我也找到了：https://github.com/nicky-chen/id-generator-spring-boot-starter/tree/d4ee4ee2e68e4d34819abbfd2f9c30169fd0a0da/lombok-enchance/src/main/java/com/nicky/lombok/adapter
